"""
Django settings for mailgunapp project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

data = open('yellowant_app_credentials.json').read()
data_json = json.loads(data)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

app_name = os.environ.get("HEROKU_APP_NAME")
BASE_URL = "https://{}.herokuapp.com".format(app_name)
SITE_PROTOCOL = "http://"
BASE_HREF = "/"


DEV_ENV = os.environ.get('ENV', 'DEV')
print(DEV_ENV)
if DEV_ENV=="DEV":
    BASE_URL = "https://160830fa.ngrok.io"
    SITE_DOMAIN_URL = "ngrok.io"
elif DEV_ENV=="HEROKU":
    BASE_URL = "https://{}.herokuapp.com/".format(app_name)
    app_name = os.environ.get("HEROKU_APP_NAME")
    SITE_DOMAIN_URL = "herokuapp.com"



YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YA_APP_ID = str(data_json['application_id'])

YELLOWANT_CLIENT_ID = str(data_json['client_id'])
YELLOWANT_CLIENT_SECRET = str(data_json['client_secret'])
YELLOWANT_VERIFICATION_TOKEN = str(data_json['verification_token'])
YELLOWANT_REDIRECT_URL = BASE_URL + "yellowantredirecturl/"






# # ### YellowAnt specific settings ###
#
# # URL to obtain oauth2 access for a YA user
# YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
#
# # URL to receive oauth2 codes from YA for user authentication.
# # As a developer, you need to provide this URL in the YA
# # developer console so that YA knows exactly where to send the oauth2 codes.
# YELLOWANT_REDIRECT_URL = BASE_URL + "/yellowantredirecturl/"
#
# # Numerical ID generated when you register your application through
# #  the YA developer console
# YA_APP_ID = "1936"
#
# # Client ID generated from the YA developer console.
# # Required to identify requests from this application to YA
# YELLOWANT_CLIENT_ID = "xuPWZtkcU4ll820vGbg1k5XplJn1ci7FbhmKBWRK"
#
# # Client secret generated from the YA developer console.
# # Required to identify requests from this application to YA
# YELLOWANT_CLIENT_SECRET = "QC70CwFr77lwo0tb0MoyVmEK6cOWlTE1a0Q24BAAITmfI9YFAUBOHLBkIAQxz7okWAQduiEMEr4EPHHDW48R3pba8SjLLWcCjRpCPKXvBXDT736HEyGGiavuukQ3BddP"
#
# # Verification token generated from the YA developer console.
# # This application can verify requests from YA as they will
# # carry the verification token
# YELLOWANT_VERIFICATION_TOKEN = "pc0LjSDCkdKw5EHgX31l1gwfbJj6yT5U407yWrdD2c8RnAPwpEg8oaxAknXDzVhtJpkcdYCTEikaEtjGiR3uuaudgmY3EsmDOqjKdeLt4qLMNqcbnqAiWYTPNLuuzWcr"
#
#
# # ### END YellowAnt specific settings ###



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_gk(yvhtqk(jiq!yl)1*w_u2p3o5w0uc@h8mfs@_*1e)36k6z+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','{}.herokuapp.com'.format(app_name)]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lib.records',
    'lib.web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mailgunapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mailgunapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mailgundb',
        'USER': 'root',
        'PASSWORD': 'vimal_1996',
        'HOST': 'localhost',
        'PORT': '',
    }
}



if DEV_ENV=="HEROKU":
    import dj_database_url
    db_from_env = dj_database_url.config()
    DATABASES['default'].update(db_from_env)
    DATABASES['default']['CONN_MAX_AGE'] = 500

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')