# Generated by Django 2.0.5 on 2018-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_mailgunusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgunusertoken',
            name='webhook_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
