# Generated by Django 2.0.5 on 2018-06-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailGunUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=32768)),
                ('user_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken')),
            ],
        ),
    ]
