# Generated by Django 2.0.5 on 2018-06-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_mailgunusertoken_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgunusertoken',
            name='apikey_login_update_flag',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
