# Generated by Django 2.0.5 on 2018-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_mailgunusertoken_apikey_login_update_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgunusertoken',
            name='domain_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
